filebeat.inputs:
  - type: filestream
    id: docker-containers
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container:
          stream: all
          format: docker

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - drop_event:
      when:
        equals:
          container.name: "e_commerce_distributed_tracing_poc-filebeat-1"
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: false
  - drop_fields:
      ignore_missing: true
      fields:
        - message
        - host
        - input
        - stream
        - timestamp
        - log
        - container.id
        - container.image
        - container.labels

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.ilm.enabled: false

# Send Filebeat's own logs to stderr only, not Elasticsearch
logging.to_files: false
logging.to_stderr: true
logging.level: warning
